### ISSUE TITLE
How to setup tag and path definition types in the UI?

### ISSUE THREAD

**Issue by KelSolaar** [roovo/obsidian-card-board#191]
Hello,

How do I setup`tag` and `path` definition types in the UI? I can do `file` just fine but not the two formers? I'm editing the `data.json` file directly atm which is not great.

Cheers,

Thomas

**Comment by roovo** [comment]
Hiya - I presume this is the problem where they are not showing in the dropdown , as per #146.

If it is then a fix is in the pipeline and will be in the next release ...trying to get a few niggles like this sorted out!  Not quite sure when the release will be as it depends a bit on how simple the various fixes I have planned take in practice :)  Expecting/hoping for it to be within a week or so.

**Comment by roovo** [comment]
I've released a new version today (0.7.6) which hopefully fixes this issue.   Please let me know if not!

Many thanks

**Comment by KelSolaar** [comment]
Thank you, this worked!

**Comment by deladriere** [comment]
Sorry, but I still can't scroll the tag filter: I have to pick one and edit data.json to pick the tag I need
I have version 0.7.6

**Comment by roovo** [comment]
> Sorry, but I still can't scroll the tag filter: I have to pick one and edit data.json to pick the tag I need I have version 0.7.6

Darn it - not sure why this would be as it's working fine for me - so need to find a way to replicate for find out why.  Sooo, what OS is this on ? Could you add a screenshot to the issue in case this helps?  Do you use any particular theme or have any css snippets enabled?

**Comment by deladriere** [comment]
I am on macOS Somovova
often, it even crashes my Obsidian completely (I have a lot of files containing tasks! just by designing a board !!
I have to recover the situation using a backup of the .json
![capture](https://github.com/roovo/obsidian-card-board/assets/2826224/c94dbd0f-0558-407f-8611-23f792d9b3eb)

I can't get access to more than 5 or 6 tags at the time so I just pick a random file and a random tag and edit the .json

**Comment by roovo** [comment]
Closing this ticket as I've created a new issue (#204) to track the issues with the limitations of the current dropdown implementation for adding filters.
